global:
  scrape_interval: 20s

scrape_configs:
  - job_name: "prometheus-monitoring"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "tns_app"

    # Override global settings
    scrape_interval: 2s

    static_configs:
      - targets: ["app:80"]
